<?php

$this->setup(array(
    'title' => 'Cancel this booking',
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<script type="text/javascript">
function showHide() {
   var div = document.getElementById('hidden_div');
   if (div.style.display == 'none') {
      div.style = 'position:absolute; top:0; right:0; bottom:0; left:0; background-color: gray; opacity: .5;';
   }
   else {
      div.style.display = 'none';
   }
}
</script>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to cancel this booking?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('square/booking/cancellation', [], ['query' => ['bid' => $this->bid, 'confirmed' => 'true']]) ?>" class="default-button" id="cancel-button" onclick="showHide();setTimeout(function(){document.getElementById('cancel-button').removeAttribute('href');}, 1);">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, cancel this booking') ?></span>
        </a>

        &nbsp;

        <a href="<?= $this->origin ?>" class="default-button squarebox-close-link"><?= $this->t('No, go back') ?></a>
    </p>
</div>

<div id="hidden_div" style="display:none" >
</div>
