<?php

$square = $this->square;
$squareType = $this->option('subject.square.type');

$dateStart = $this->dateStart;
$dateEnd = $this->dateEnd;

$this->setup(array(
    'title' => sprintf('%s-%s', $squareType, $this->t('Booking')),
    'panel' => 'centered-panel',
    'messages' => array(
        'error' => $this->message,
    ),
    'back' => true,
));

?>

<script type="text/javascript">
function showHide() {
   var div = document.getElementById('hidden_div');
   if (div.style.display == 'none') {
     div.style = 'position:absolute; top:0; right:0; bottom:0; left:0; background-color: gray; opacity: .5;';
   }
   else {
     div.style.display = 'none';
   }
}
</script


<div class="padded">

    <form id="confirmform" method="post" onSubmit="showHide();" action="<?= $this->url ?>">
<?php

        $pricingSummary = $this->squarePricingSummary($dateStart, $dateEnd, $square, $this->quantityChoosen, $this->products);

        if ($pricingSummary) {
            echo '<p class="centered-text gray"><em>' . $this->t('Summary of your booking:') . '</em></p>';
            echo '<div class="sandbox">' . $pricingSummary . '</div>';
            echo '<div class="separator separator-line"></div>';
        }

        ?>

        <?php if ($square->getMeta('rules.document.file')): ?>

            <p class="symbolic symbolic-warning"><b><?= $this->t('Please note') ?>:</b></p>

            <p style="margin-left: 32px;">
                <a href="<?= $this->basePath($square->getMeta('rules.document.file')) ?>" class="default-button" target="_blank">
                    <span class="symbolic symbolic-attachment"><?= $square->getMeta('rules.document.name', $this->t('Rules-document')) ?></span>
                </a>

                <span class="small-text gray">(<?= $this->t('this will open in a new window') ?>)</span>
            </p>

            <div style="margin-left: 32px;">
                <input type="checkbox" name="bf-accept-rules-document" id="bf-accept-rules-document">
                <label for="bf-accept-rules-document"><?= sprintf($this->t('Yes, I have %1$sread and accepted%2$s the "%3$s"'), '<b>', '</b>', $square->getMeta('rules.document.name', $this->t('Rules-document'))) ?></label>
            </div>

            <div class="separator separator-line"></div>

        <?php endif; ?>

        <?php if ($square->getMeta('rules.text')): ?>

            <p class="symbolic symbolic-warning"><b><?= $this->t('Please note') ?>:</b></p>

            <div style="margin-left: 32px;"><?= $square->getMeta('rules.text') ?></div>

            <div style="margin-left: 32px;">
                <input type="checkbox" name="bf-accept-rules-text" id="bf-accept-rules-text">
                <label for="bf-accept-rules-text"><?= sprintf($this->t('Yes, I have %sread and accepted%s these rules and notes'), '<b>', '</b>') ?></label>
            </div>

            <div class="separator separator-line"></div>

        <?php endif; ?>

        <div class="centered-text big-text gray" style="margin-bottom: 12px;"><b>
	        <?php

	        $cancelRange = $square->need('range_cancel');

	        if ($cancelRange) {

		        printf($this->t('Your booking will be binding, however, you can cancel it up to %s before it takes place.'),
                    $this->prettyTime($cancelRange));
	        } else {

		        echo $this->t('Your booking will be binding.');
	        }

	        ?>
        </b></div>

        <div class="centered-text">
            <input type="hidden" name="bf-confirm" value="<?= sha1('Quick and dirty' . floor(time() / 1800)) ?>">   

            <?php if ($this->payable): ?>

            <?php if ($this->paypal): ?>     
                <label for="paypal" class="payment_radio">
                <input type="radio" id="paypal" name="paymentservice" value="paypal" <?php if ($this->payment_default == 'paypal'): ?>checked<?php endif; ?>  onclick="if(this.checked){document.getElementById('bf-submit').value='<?= $this->t('go to payment') ?>'}">
                    <img width="80" height="60" src="<?= $this->basePath('imgs-client/layout/paypal.png') ?>" border="0" alt="PayPal Logo" />
                    </label>
            <?php endif; ?>
            <?php if ($this->stripe): ?>
                <label for="stripe" class="payment_radio">
                <input type="radio" id="stripe" name="paymentservice" value="stripe" <?php if ($this->payment_default == 'stripe'): ?>checked<?php endif; ?> onclick="if(this.checked){document.getElementById('bf-submit').value='<?= $this->t('go to payment') ?>'}">
                    <img width="80" height="60" src="<?= $this->basePath('imgs-client/layout/stripe_icons/'.$this->stripeIcon) ?>" border="0" alt="Stripe Logo" />
                    </label>
            <?php endif; ?>
            <?php if ($this->klarna): ?>
                <label for="klarna" class="payment_radio">
                <input type="radio" id="klarna" name="paymentservice" value="klarna" <?php if ($this->payment_default == 'klarna'): ?>checked<?php endif; ?> onclick="if(this.checked){document.getElementById('bf-submit').value='<?= $this->t('go to payment') ?>'}">
                    Klarna
                    </label>
            <?php endif; ?> 

            <?php if ($this->billing): ?>
                <label for="billing" class="payment_radio">
                <input type="radio" id="billing" name="paymentservice" value="billing" <?php if ($this->payment_default == 'billing'): ?>checked<?php endif; ?> onclick="if(this.checked){document.getElementById('bf-submit').value='<?= $this->t('Complete booking') ?>'}">
                <img width="80" height="60" src="<?= $this->basePath('imgs-client/layout/rechnung.svg') ?>" border="0" alt="Bill Logo" />  
                </label>
            <?php endif; ?>
 
            <?php if ($this->paypal || $this->stripe || $this->klarna): ?>
                <br>
                <br>
                <input type="submit" name="bf-submit" id="bf-submit" value="<?= $this->t('go to payment') ?>" class="default-button">
            <?php else: ?>
                <input type="submit" name="bf-submit" id="bf-submit" value="<?= $this->t('Complete booking') ?>" class="default-button">
            <?php endif; ?>                       

            <?php else: ?>
                <br>
                <br>
                <input type="submit" name="bf-submit" id="bf-submit" value="<?= $this->t('Complete booking') ?>" class="default-button">
            <?php endif; ?>  
        </div>

    </form>

</div>

<div id="hidden_div" style="display:none" >
</div>
