<?php

$this->setup(array(
    'title' => 'Terms & Conditions',
    'panel' => 'centered-panel large-sized',
    'back' => true,
    'links' => array(
        'Help' => $this->url('service/help'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/controller/service/term.min.js'));

?>

<div id="term-panel">
    <h1><?= $this->t('Terms & Conditions') ?></h1>

    <div class="separator-small"></div>

    <?= $this->option('subject.term', '<p><em>' . $this->t('We are currently working on this page.') . '</em></p>') ?>
</div>