<?php
use \Square\Factory\Cart;

$square = $this->square;
$squareType = $this->option('subject.square.type');

$this->setup(array(
    'title' => sprintf('%s-%s', $squareType, $this->t('Details')),
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<div class="padded centered-text">

    <?php

    // $cartService = Cart::getInstance();
    // $cartItems = $cartService->getItems();

    // syslog(LOG_EMERG, print_r($cartItems, true));
    // syslog(LOG_EMERG, print_r($square->need('sid'), true));
    // syslog(LOG_EMERG, print_r($this->dateStart , true));

    //Need to do a match between cartItems elements and dateStart, sid, dateEnd

    if ($square->getMeta('info.pre')) {
        echo $square->getMeta('info.pre');
        echo '<div class="separator separator-line"></div>';
    }

    ?>

    <p class="large-text"><?= $squareType . ' ' . $this->t($square->need('name')) ?></p>

    <?= $this->squareDateFormat($this->dateStart, $this->dateEnd) ?>

    <?php if ($this->bookingsFromUser && $this->flag != 'fb'): ?>
        <?= $this->partial('square/square/index.own.phtml', $this->vars()) ?>
    <?php elseif ($this->bookable): ?>
        <?= $this->partial('square/square/index.free.phtml', $this->vars()) ?>
    <?php /*elseif ($this->bookable): ?>
        <?= $this->partial('user/account/cart.phtml', $cartItems) */?> 
    <?php else: ?>
        <?= $this->partial('square/square/index.occupied.phtml', $this->vars()) ?>
    <?php endif; ?>
 
    <?php

    if ($square->getMeta('info.post')) {
        echo '<div class="separator separator-line"></div>';
        echo $square->getMeta('info.post');
    }

    ?>

</div>