<!DOCTYPE html>
<html lang="<?= $this->config('i18n.locale') ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="format-detection" content="telephone=no">
        <meta name="generator" content="<?= $this->option('service.branding.name') ?>">
        <meta name="publisher" content="<?= $this->option('client.name.full') ?>">
        <meta name="description" content="<?= $this->option('service.meta.description') ?>">
        
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="<?= $this->option('service.name.full') ?>" />
        
        <link rel="manifest" href="<?= $this->basePath('manifest.webmanifest') ?>" />
        
        <link type="image/x-icon" rel="icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
        <link type="image/x-icon" rel="shortcut icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/jquery-ui/jquery-ui.min.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/default_2.2.min.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css-client/default.min.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css-client/font-awesome-4.7.0/css/font-awesome.min.css') ?>" media="screen">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css-client/tennis-rudolstadt_2.2.min.css') ?>" media="all">
        <?= $this->headLink() ?>
        <?= $this->headTitle($this->option(['client.name.short', 'service.name.full']))->setSeparator(' &middot; ')->setAutoEscape(false) ?>
    </head>

    <body class="tennis-rudolstadt">
        <div id="header" class="no-wrap no-print" <?= $this->headerAttributes() ?>>
            <div id="label">
                <a href="<?= $this->basePath('/') ?>" id="logo"></a>

                <div id="label-client">
                    <a href="<?= $this->option('client.website') ?>" target="_blank" class="unlined white">
                    <?= $this->option('client.name.full') ?>
                    </a>
                </div>
                <div id="label-service"><?= $this->option('service.name.full') ?></div>
                <div id="label-service-phone">
                    <span class="phone-icon fa fa-phone"></span>
                    <a href="tel:<?= $this->option('client.contact.phone') ?>" class="unlined white">
                        <?= $this->option('client.contact.phone') ?>
                    </a>
                </div>
            </div>

            <div id="topbar">
                <?= $this->headerLocaleChoice() ?>

                <div id="topbar-phone" class="topbar-item responsive-pass-4">
                    <p>
                        <span class="topbar-label"><?= $this->t('Book by phone') ?></span><br>
                        <span class="topbar-text large-text">
                            <a href="tel:<?= $this->option('client.contact.phone') ?>" class="unlined white">
                                <?= $this->option('client.contact.phone') ?>
                            </a>
                        </span>
                    </p>
                </div>

            </div>
        </div>

        <div id="content">
            <?= $this->messages() ?>

            <?= $this->tabs() ?>

            <div class="content-panel <?= $this->placeholder('panel') ?>" style="overflow-y:hidden;">
                <?= $this->content ?>
            </div>

            <?= $this->links() ?>
        </div>

        <div id="footer">
            <div class="centered-text">
                <span class="no-wrap">&copy; <?= date('Y') ?> <a href="<?= $this->option('client.website') ?>" target="_blank"><?= $this->option('client.name.full') ?></a></span>
                (<a href="<?= $this->option('client.website.imprint') ?>" target="_blank"><?= $this->t('Imprint') ?></a><?php if ($this->option('client.website.privacy')): ?> &ndash; <a href="<?= $this->option('client.website.privacy') ?>" target="_blank"><?= $this->t('Privacy') ?></a><?php endif; ?>
        &ndash; <a href="<?= $this->option('client.website.contact') ?>" target="_blank">
        <?= $this->t('Contact & Feedback') ?></a>)
                <?php if ($this->option('service.branding', 'true') == 'true'): ?>
                <span class="no-wrap">&amp; <a href="<?= $this->option('service.branding.website') ?>" target="_blank"><?= $this->option('service.branding.name') ?></a> (<?= $this->t('Software') ?>)</span>
                <?php endif; ?>
            </div>
        </div>

        <script type="text/javascript" src="<?= $this->basePath('js/jquery/jquery.min.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/jquery-ui/jquery-ui.min.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/default.min.js') ?>"></script>
        <?= $this->headScript() ?>
        <script type="text/javascript" src="<?= $this->basePath('js-client/tennis-rudolstadt.min.js') ?>"></script>

<!-- swipe calendar with hammer.js -->

<script type="text/javascript" src="<?= $this->basePath('js/controller/frontend/hammer.min.js') ?>"></script>
<script type="text/javascript">

var nextdateelement =  document.getElementById('nextdatearrow');
if (typeof(nextdateelement) != 'undefined' && nextdateelement != null)
{
// Hammer.js Swipe Functionality
    var mc = new Hammer.Manager(document.body, {
       touchAction: "pan-y"
    });
var Swipe = new Hammer.Swipe();
mc.add(Swipe);
mc.on('swiperight', function () {
   document.getElementById('prevdatearrow').click();
});
mc.on('swipeleft', function () {
   document.getElementById('nextdatearrow').click();
});
}
</script>

<script type="text/javascript">
// Register the PWA service worker if available.
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('<?= $this->basePath('js/sw.js') ?>').then(function(reg) {
        console.log('Successfully registered service worker', reg);
    }).catch(function(err) {
        console.warn('Error whilst registering service worker', err);
    });
}
</script>

</body>
</html>