<?php

$this->setup(array(
    'title' => 'Terms & Conditions page',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Configuration' => $this->url('backend/config'),
    ),
    'links' => array(
        'Info page' => $this->url('backend/config/info'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.setup.js'));

?>

<div>
    <h1><?= $this->t('Terms & Conditions page') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('Which text should appear on the Terms & Conditions page?') ?></p>

    <?= $this->backendInfo('i18n') ?>

    <div class="separator-small"></div>

    <form method="post" action="<?= $this->url('backend/config/term') ?>">
        <div>
            <textarea name="cf-term" id="cf-term" class="wysiwyg-editor" style="height: 600px;">
                <?= $this->option('subject.term') ?>
            </textarea>
        </div>
    </form>
</div>