<?php

$this->setup(array(
    'title' => 'My bookings',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'My account' => $this->url('user/settings'),
    ),
));

?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<div>
    <h1><?= $this->translate('Booking Cart') ?></h1>

    <div class="separator-small"></div>

    <?php if (count($this->cartItems) == 0): ?>
        <p><?= sprintf($this->translate('Your cart is empty.')) ?></p>
    <?php elseif (count($this->cartItems) == 1): ?>
        <p><?= sprintf($this->translate('You have one item in your cart.')) ?></p>
    <?php else: ?>
        <p><?= sprintf($this->translate('You have %s items in your cart.'), count($this->cartItems)) ?></p>
    <?php endif; ?>

    <?php if (count($this->cartItems) > 0): ?>

        <div class="separator separator-line"></div>

        <style type="text/css">
            .default-table td { padding-right: 16px; padding-bottom: 8px; height: 24px; }
        </style>

        <table class="default-table middle-table">
            <tr> <!-- Add a row for column names -->
                <td style="color: black;">Court</td>
                <td style="color: black;">Date</td>
                <td style="color: black;">Time Slot</td>
                <td style="color: black;">Price</td>
                <td></td> <!-- Empty column for remove button -->
            </tr>
            <?php foreach ($this->cartItems as $index => $cartItem): ?>
                <tr>
                    <td style="color: black;"><?= $cartItem['squareName'] ?></td>
                    <td style="color: black;"><?= substr($cartItem['start'], 0, -8) ?></td>
                    <td style="color: black;"><?= substr($cartItem['start'], -8, -3) ,'-' ,substr($cartItem['end'], -8, -3) ?></td>
                    <td style="color: black;">$<?= number_format($cartItem['price']/100, 2) ?></td>
                    <td>
                        <a href="<?php echo $this->url('user/cart/remove-item', array('index' => $index)); ?>" class="btn btn-danger btn-sm">
                            <i class="fas fa-trash-alt"></i> Remove
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>

        <div class="separator-small"></div>

        <!-- Calculate and display total price -->
        <?php
            $totalPrice = 0;
            foreach ($this->cartItems as $cartItem) {
                $totalPrice += $cartItem['price'];
            }
        ?>
        <p style="text-align: center; font-size: large;">Total Price: $<?= number_format($totalPrice/100, 2) ?></p>

        <!-- Add the checkout button -->
        <div style="text-align: center; margin-top: 20px;">
            <a href="<?= $this->url('square/booking/checkout') ?>"class="default-button">Checkout to Payment</a>
        </div>

    <?php endif; ?>

</div>