<table style="height: 100%;">
    <tr>
        <td class="responsive-pass-up" style="padding-right: 12px; border-right: solid 1px #CCC;">
            <div id="userpanel-status" class="no-wrap">
                <?= sprintf($this->t('Online as %s'), $this->user->need('alias')) ?>
            </div>
        </td>

        <td class="responsive-pass-up" style="padding-right: 12px;"></td>

        <?php if ($this->user->can('admin.see-menu')): ?>

            <?php $this->headScript()->appendFile($this->basePath('js/controller/frontend/index.admin.min.js')) ?>

            <td class="responsive-pass-up never-hide-table-cell" style="padding-right: 12px; border-right: solid 1px #CCC;">
                <a href="<?= $this->url('backend') ?>" id="admin-menu-link" class="default-button"><span class="symbolic symbolic-config">&nbsp;<span class="symbolic-label"><?= $this->t('Administration') ?></span></span></a>
            </td>

            <td class="responsive-pass-up never-hide-table-cell" style="padding-right: 12px;"></td>

        <?php endif; ?>

        <td>
            <a href="<?= $this->url('user/bookings') ?>" class="default-button" data-tooltip="<?= $this->userLastBookings($this->user) ?>">
                <span class="symbolic symbolic-booking">&nbsp;<span class="symbolic-label"><?= $this->t('My bookings') ?></span></span>
            </a>
        </td>

        <td>
            <a href="<?= $this->url('user/cart') ?>" class="default-button">
                <span class="symbolic symbolic-cart">&nbsp;<span class="symbolic-label"><?= $this->t('Booking cart') ?></span></span>
            </a>
        </td>

        <td>
            <a href="<?= $this->url('user/settings') ?>" class="default-button">
                <span class="symbolic symbolic-user">&nbsp;<span class="symbolic-label"><?= $this->t('My account') ?></span></span>
            </a>
        </td>

        <td style="padding-right: 12px;">
            <a href="<?= $this->url('user/logout') ?>" class="default-button">
                <span class="symbolic symbolic-off">&nbsp;<span class="symbolic-label"><?= $this->t('Logout') ?></span></span>
            </a>
        </td>

        <td style="padding-left: 12px; border-left: solid 1px #CCC;">
            <a href="<?= $this->url('service/help') ?>" class="default-button" data-tooltip="<?= sprintf($this->t('Get additional %shelp and information%s'), '<b>', '</b>') ?>"><b>?</b></a>
        </td>
    </tr>
</table>
